package config

import("errors";"flag";"fmt";"net";"net/url";"os";"path/filepath";"strconv";"strings")
type Action int
const(ActionRun Action=iota;ActionLogin;ActionLogout;ActionVersion)
type Config struct{Issuer,ClientID,Scope,Upstream,Listen,RedirectPort,TokenStore string;Login bool}
func Parse(args []string,getenv func(string)string)(Config,Action,error){c:=Config{Listen:"127.0.0.1:8080"}; f:=flag.NewFlagSet("oauth2-sidecar",flag.ContinueOnError); f.SetOutput(os.Stderr); var login,logout,version bool
 f.StringVar(&c.Issuer,"issuer",getenv("OAUTH2_SIDECAR_ISSUER"),"OIDC issuer URL");f.StringVar(&c.ClientID,"client-id",getenv("OAUTH2_SIDECAR_CLIENT_ID"),"OAuth client ID");f.StringVar(&c.Scope,"scope",or(getenv("OAUTH2_SIDECAR_SCOPE"),"openid profile offline_access"),"OAuth scopes");f.StringVar(&c.Upstream,"upstream",getenv("OAUTH2_SIDECAR_UPSTREAM"),"upstream URL");f.StringVar(&c.Listen,"listen",or(getenv("OAUTH2_SIDECAR_LISTEN"),c.Listen),"listen address");f.StringVar(&c.RedirectPort,"redirect-port",getenv("OAUTH2_SIDECAR_REDIRECT_PORT"),"callback port");f.StringVar(&c.TokenStore,"token-store",getenv("OAUTH2_SIDECAR_TOKEN_STORE"),"token path");f.BoolVar(&login,"login",false,"force login");f.BoolVar(&logout,"logout",false,"delete token");f.BoolVar(&version,"version",false,"print version")
 if err:=f.Parse(args);err!=nil{return c,ActionRun,err};if version{return c,ActionVersion,nil};if login&&logout{return c,ActionRun,errors.New("--login and --logout cannot be combined")};if logout{return c,ActionLogout,nil};c.Login=login;if c.Issuer==""||c.ClientID==""||c.Upstream==""{return c,ActionRun,errors.New("--issuer, --client-id, and --upstream are required")}
 for n,s:=range map[string]string{"issuer":c.Issuer,"upstream":c.Upstream}{u,e:=url.Parse(s);if e!=nil||u.Scheme!="https"||u.Host==""{return c,ActionRun,fmt.Errorf("--%s must be an absolute HTTPS URL",n)}};if _,_,e:=net.SplitHostPort(c.Listen);e!=nil{return c,ActionRun,fmt.Errorf("--listen must be host:port: %w",e)};if c.RedirectPort!=""{if _,e:=strconv.Atoi(c.RedirectPort);e!=nil{return c,ActionRun,errors.New("--redirect-port must be numeric")}};if c.TokenStore==""{d,e:=os.UserConfigDir();if e!=nil{return c,ActionRun,e};c.TokenStore=filepath.Join(d,"oauth2-sidecar","token.json")};if strings.TrimSpace(c.Scope)==""{return c,ActionRun,errors.New("--scope cannot be empty")};return c,ActionRun,nil}
func or(v,d string)string{if strings.TrimSpace(v)==""{return d};return v}
